from app.models import db, Disc

# Adds a demo user, you can add other users here if you want
def seed_discs():

    disc1 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://www.innovadiscs.com/wp-content/uploads/2014/11/Blizzard-Destroyer.jpg", "img-url2"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc2 = Disc(name="Boss", brand_id=2, speed=13, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/6049208.png", price=13.95, description="This is a fast stable driver that can handle full power throws and moderate headwinds. Advanced players and sidearm throwers will appreciate the dependable stability. The Boss has a slight high speed turn to help maximize distance with a predictable fade. David Wiggins Jr used a 154 gram R-Pro Boss to set the World Record 338 M (1108.92 feet) for the longest throw in March 2016.", images=["https://www.innovadiscs.com/wp-content/uploads/2015/02/CH-Boss.jpg", "img-url2"], type_id=1, stability_id=1, diameter=21.1, height=1.5, rim_depth=1.2, rim_width=2.5, max_weight=184.0)
    disc3 = Disc(name="Hades", brand_id=1, speed=12, glide=6, turn=-3, fade=2, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2613404.png", price=24.99, description="The Hades is the newest Paul McBeth Series Driver. It's a straight to understable driver with massive amounts of glide. The Hades will be your new go-to distance driver, especially if you are intermediate to advanced. Players with bigger arms will find this to be an awesome, long bomb understable disc that will glide for days.", images=["https://static.wixstatic.com/media/b32cf7_fded1b9bb0fc41009435a0a93eb92d07~mv2.jpg", "https://images-na.ssl-images-amazon.com/images/I/71odOQea4uL._AC_SL1500_.jpg"], type_id=1, stability_id=3, diameter=21.0, height=1.6, rim_depth=1.1, rim_width=2.3, max_weight=174.0)
    disc4 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/61ik5YYga3L._AC_SL1000_.jpg", "img-url2"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc5 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/61FGx3S9OAL._AC_SL1000_.jpg"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc6 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/51EnWKQSPLL._AC_SL1001_.jpg"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc7 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/71CJlvHBE8L._AC_SL1500_.jpg"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc8 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/611WQYfty0L._AC_SL1001_.jpg"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc9 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/71B4%2Bb%2BcwQL._AC_SL1500_.jpg"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)
    disc10 = Disc(name="Destroyer", brand_id=2, speed=12, glide=5, turn=-1, fade=3, flight_path="https://infinitediscs.com/Inf_Uploads/FlightPath_Images/2079719.png", price=13.99, description="The Destroyer is a very fast stable long distance driver. This disc is much like a faster Wraith, but with a little more high and low speed stability. Great disc for sidearm throwers and those with lots of power. Can handle headwinds and throws with off axis torque. Not suggested for beginning players.", images=["https://images-na.ssl-images-amazon.com/images/I/5177qZhWtWL._AC_SL1000_.jpg"], type_id=1, stability_id=2, diameter=21.1, height=1.4, rim_depth=1.2, rim_width=2.2, max_weight=178.0)

    db.session.add(disc1)
    db.session.add(disc2)
    db.session.add(disc3)
    db.session.add(disc4)
    db.session.add(disc5)
    db.session.add(disc6)
    db.session.add(disc7)
    db.session.add(disc8)
    db.session.add(disc9)
    db.session.add(disc10)

    db.session.commit()

# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_discs():
    db.session.execute('TRUNCATE discs CASCADE;')
    db.session.commit()
